# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: Mark Cornick <mcornick@mcornick.com>

pkgname='mpg-bin'
pkgver=1.2.1
pkgrel=1
pkgdesc='Mark's Password Generator'
url='https://mcornick.com/mpg/'
arch=('aarch64' 'armv6h' 'i686' 'x86_64')
license=('MIT')
provides=('mpg')
conflicts=('mpg')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/mcornick/mpg/releases/download/v1.2.1/mpg_1.2.1_linux_arm64.tar.gz")
sha256sums_aarch64=('0d488a40ced00138401936aeceeac1f01069691b110056b932b37f6f07255173')

source_armv6h=("${pkgname}_${pkgver}_armv6h.tar.gz::https://github.com/mcornick/mpg/releases/download/v1.2.1/mpg_1.2.1_linux_armv6.tar.gz")
sha256sums_armv6h=('73a815618b75524c868d89f1e4f962e1b6cbe5582d965529f8d3432bb591a635')

source_i686=("${pkgname}_${pkgver}_i686.tar.gz::https://github.com/mcornick/mpg/releases/download/v1.2.1/mpg_1.2.1_linux_386.tar.gz")
sha256sums_i686=('5b274e31a2d403a0c6c5feae1c1046662d55dc11a4fd590a419a84527cede04d')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/mcornick/mpg/releases/download/v1.2.1/mpg_1.2.1_linux_amd64.tar.gz")
sha256sums_x86_64=('9814ebe8fb8b252d37e952a86665819c0b528f29eda3c0b9482c18c99cef52a1')

package() {
  install -Dm755 "./mpg" "${pkgdir}/usr/bin/mpg"
  install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/mpg/LICENSE"
  mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
  mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
  mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
  install -Dm644 "./completions/mpg.bash" "${pkgdir}/usr/share/bash-completion/completions/mpg"
  install -Dm644 "./completions/mpg.zsh" "${pkgdir}/usr/share/zsh/site-functions/_mpg"
  install -Dm644 "./completions/mpg.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/mpg.fish"
  install -Dm644 "./manpage/mpg.1" "${pkgdir}/usr/share/man/man1/mpg.1"
}
